<?php

namespace Chema\ArsBundle\Entity;

use Doctrine\DBAL\Query\QueryBuilder;
use Assetic\Exception\Exception;

/**
 * VoucherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoucherRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * findAllOrderedDateFound
	 */
	public function findAllOrderedDateFound()
	{
		return $this->getEntityManager()
			->createQuery(
					'SELECT v FROM ChemaArsBundle:Voucher v ORDER BY v.dateFound DESC'
			)
			->getResult();
	}

	/**
	 * getTotal
	 */
	public function getTotal()
	{
		return $this->getEntityManager()
			->createQuery(
					'SELECT count(v.id) FROM ChemaArsBundle:Voucher v'
			)
			->getSingleScalarResult();
	}
}
